{% set name = "iota" %}
{% set version = "1.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef271c4a8bf1f4cd1d9132d266632e332ce77acaca2b0eafaa73f491d8c86b17

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - setuptools
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - iota

about:
  home: https://github.com/ssrl-px/iota
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'IOTA: Integration Optimization, Triage and Analysis'
  description: |
    IOTA is a user-friendly front end for dials.stills_process,
    a serial diffraction data processing program.
  dev_url: https://github.com/ssrl-px/iota

extra:
  recipe-maintainers:
    - alyubimov
    - Anthchirp
